org.gradle.daemon=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false

# Tăng bộ nhớ cho Gradle Daemon (Rất hiệu quả)
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Cho phép build song song các module
org.gradle.parallel=true

# Sử dụng lại các kết quả build trước đó (Build Cache)
org.gradle.caching=true

# Cấu hình Gradle chỉ thực hiện những task thay đổi
org.gradle.configureondemand=true

# Tăng tốc độ cho Kotlin
kotlin.incremental=true
kotlin.incremental.usePreciseJavaTracking=true